### ISSUE TITLE
crash on `typing_extensions.py`

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedmypy#110]
tryna add basedmypy to http://github.com/kotlinisland/basedtyping be like

```
.\typing_extensions\src\test_typing_extensions.py:1789: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.1.3
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\Scripts\mypy.exe\__main__.py", line 7, in <module>
    sys.exit(console_entry())
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\main.py", line 96, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\main.py", line 179, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\build.py", line 180, in build
    result = _build(
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\build.py", line 256, in _build
    graph = dispatch(sources, manager, stdout)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\build.py", line 2729, in dispatch
    process_graph(graph, manager)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\build.py", line 3060, in process_graph
    process_stale_scc(graph, scc, manager)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\build.py", line 3152, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal_main.py", line 79, in semantic_analysis_for_scc
    process_functions(graph, scc, patches)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal_main.py", line 233, in process_functions
    process_top_level_function(analyzer,
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal_main.py", line 274, in process_top_level_function
    deferred, incomplete, progress = semantic_analyze_target(target, state, node, active_type,
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal_main.py", line 326, in semantic_analyze_target
    analyzer.refresh_partial(refresh_node,
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal.py", line 408, in refresh_partial
    self.accept(node)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal.py", line 5092, in accept
    node.accept(self)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\nodes.py", line 727, in accept
    return visitor.visit_func_def(self)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal.py", line 621, in visit_func_def
    self.analyze_func_def(defn)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal.py", line 664, in analyze_func_def
    self.analyze_function_body(defn)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal.py", line 994, in analyze_function_body
    defn.body.accept(self)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\nodes.py", line 1069, in accept
    return visitor.visit_block(self)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal.py", line 3531, in visit_block
    self.accept(s)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal.py", line 5092, in accept
    node.accept(self)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\nodes.py", line 1366, in accept
    return visitor.visit_with_stmt(self)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal.py", line 3680, in visit_with_stmt
    self.visit_block(s.body)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal.py", line 3531, in visit_block
    self.accept(s)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal.py", line 5092, in accept
    node.accept(self)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\nodes.py", line 1000, in accept
    return visitor.visit_class_def(self)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal.py", line 1105, in visit_class_def
    self.analyze_class(defn)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal.py", line 1127, in analyze_class
    bases, tvar_defs, is_protocol = self.clean_up_bases_and_infer_type_variables(
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal.py", line 1337, in clean_up_bases_and_infer_type_variables
    all_tvars = self.get_all_bases_tvars(base_type_exprs, removed)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\semanal.py", line 1428, in get_all_bases_tvars
    base_tvars = base.accept(TypeVarLikeQuery(self.lookup_qualified, self.tvar_scope))
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\types.py", line 615, in accept
    return visitor.visit_unbound_type(self)
  File "C:\Users\user\IdeaProjects\basedtyping\.venv\lib\site-packages\mypy\typeanal.py", line 1296, in visit_unbound_type
    return self.query_types([t.args[0]])
IndexError: tuple index out of range
.\typing_extensions\src\test_typing_extensions.py:1789: : note: use --pdb to drop into pdb
```

```
basedmypy 2.0.0+dev.41706dcab733a05a6f43d4739832508cda54c4ad
mypy 0.940+dev.41706dcab733a05a6f43d4739832508cda54c4ad
```

**Comment by DetachHead** [comment]
nvm this is an upstream issue https://github.com/python/mypy/issues/11808

**Comment by KotlinIsland** [comment]
Close this then?

**Comment by DetachHead** [comment]
i think leave open until we have the fix in our fork... tho idk the best way to manage upstream issues so we can just close this if u think its better to just do that

**Comment by KotlinIsland** [comment]
I don't see any purpose to duplicating that issue here.
