### ISSUE TITLE
ignore baseline flag(`--ignore-baseline`)

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedmypy#95]

**Comment by KotlinIsland** [comment]
currently you can do `--baseline-file /dev/null`

**Comment by KotlinIsland** [comment]
@DetachHead What would you expect this to be? perhaps `--no-baseline`?

**Comment by DetachHead** [comment]
`--ignore-baseline` i think

**Comment by KotlinIsland** [comment]
@DetachHead does the newer functionality of `--baseline-file=` meet this feature request?

**Comment by DetachHead** [comment]
how would you tell it to not check the baseline file at all

**Comment by KotlinIsland** [comment]
`mypy --baseline-file= src/`

**Comment by DetachHead** [comment]
doesn't work
```
(.venv) PS C:\Users\amogus\basedtyping> mypy --baseline-file= .
Traceback (most recent call last):
  File "C:\Users\amogus\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\amogus\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\amogus\basedtyping\.venv\Scripts\mypy.exe\__main__.py", line 7, in <module>
  File "C:\Users\amogus\basedtyping\.venv\lib\site-packages\mypy\__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "C:\Users\amogus\basedtyping\.venv\lib\site-packages\mypy\main.py", line 96, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "C:\Users\amogus\basedtyping\.venv\lib\site-packages\mypy\main.py", line 179, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "C:\Users\amogus\basedtyping\.venv\lib\site-packages\mypy\build.py", line 180, in build
    result = _build(
  File "C:\Users\amogus\basedtyping\.venv\lib\site-packages\mypy\build.py", line 256, in _build
    graph = dispatch(sources, manager, stdout)
  File "C:\Users\amogus\basedtyping\.venv\lib\site-packages\mypy\build.py", line 2724, in dispatch
    process_graph(graph, manager)
  File "C:\Users\amogus\basedtyping\.venv\lib\site-packages\mypy\build.py", line 3055, in process_graph
    process_stale_scc(graph, scc, manager)
  File "C:\Users\amogus\basedtyping\.venv\lib\site-packages\mypy\build.py", line 3173, in process_stale_scc
    res = manager.errors.load_baseline(Path(manager.options.baseline_file))
  File "C:\Users\amogus\basedtyping\.venv\lib\site-packages\mypy\errors.py", line 823, in load_baseline
    self.baseline = json.load(file.open("r"))
  File "C:\Users\amogus\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '.'
```

**Comment by KotlinIsland** [comment]
It's a 1.3 feature
